//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tArticle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tArticle()
        {
            this.tIdentity = new HashSet<tIdentity>();
        }
    
        public int f文章編號 { get; set; }
        public string f文章區使用者編號 { get; set; }
        public string f文章標題 { get; set; }
        public Nullable<int> f文章讚數 { get; set; }
        public string f文章地點 { get; set; }
        public string f文章分類 { get; set; }
        public string f文章結束日期 { get; set; }
        public string f文章發文日期 { get; set; }
        public string f文章發文內容 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tIdentity> tIdentity { get; set; }
    }
}
