//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tArticle
    {
        public int f文章編號 { get; set; }
        public string f帳號 { get; set; }
        public string f大頭貼路徑 { get; set; }
        public string f標題 { get; set; }
        public Nullable<int> f點讚 { get; set; }
        public string f地點 { get; set; }
        public string f分類 { get; set; }
        public string f結束日期 { get; set; }
        public string f發文日期 { get; set; }
        public string f發文內容 { get; set; }
    }
}
