//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tEat
    {
        public int f飯局編號 { get; set; }
        public string f帳號 { get; set; }
        public string f暱稱 { get; set; }
        public string f大頭貼 { get; set; }
        public string f團圖 { get; set; }
        public string f內容 { get; set; }
        public Nullable<int> f點讚次數 { get; set; }
        public Nullable<System.DateTime> f建立時間 { get; set; }
        public string f開團標題 { get; set; }
        public Nullable<System.DateTime> f活動開始時間 { get; set; }
        public string f地點 { get; set; }
        public Nullable<decimal> f預算 { get; set; }
        public string f分類 { get; set; }
        public HttpPostedFileBase fImgPath { get; set; }
    }
}
