//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tEat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tEat()
        {
            this.tIdentity = new HashSet<tIdentity>();
        }
    
        public int f飯局編號 { get; set; }
        public string f飯局區使用者編號 { get; set; }
        public string f飯局發文日期 { get; set; }
        public string f飯局活動開始時間 { get; set; }
        public string f飯局活動結束時間 { get; set; }
        public string f飯局招募截止時間 { get; set; }
        public string f飯局標題 { get; set; }
        public string f飯局內容 { get; set; }
        public string f飯局地區 { get; set; }
        public string f飯局預算 { get; set; }
        public string f飯局瀏覽次數 { get; set; }
        public string f飯局讚數 { get; set; }
        public string f飯局分類 { get; set; }
        public string f飯局標籤 { get; set; }
        public string f飯局團圖 { get; set; }
        public string f飯局按過讚的會員編號 { get; set; }
        public string f飯局經度 { get; set; }
        public string f飯局緯度 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tIdentity> tIdentity { get; set; }
    }
}
