//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tIdentity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tIdentity()
        {
            this.tMember = new HashSet<tMember>();
        }
    
        public int f會員編號 { get; set; }
        public string f文章區使用者編號 { get; set; }
        public string f旅遊區使用者編號 { get; set; }
        public string f飯局區使用者編號 { get; set; }
        public string f聯絡我們使用者編號 { get; set; }
        public string f留言功能使用者編號 { get; set; }
    
        public virtual tArticle tArticle { get; set; }
        public virtual tEat tEat { get; set; }
        public virtual tTravel tTravel { get; set; }
        public virtual t留言 t留言 { get; set; }
        public virtual t聯絡我們 t聯絡我們 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tMember> tMember { get; set; }
    }
}
