//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMember
    {
        public int f會員編號 { get; set; }      //uerId
        public string f會員名稱 { get; set; }
        public string f會員評分 { get; set; }
        public string f會員稱號 { get; set; }
        public string f會員大頭貼 { get; set; }
        public string f會員帳號 { get; set; }
        public string f會員密碼 { get; set; }
        public string f會員密碼確認 { get; set; }
        public string f電子郵件 { get; set; }
        public string f手機 { get; set; }
        public string f電話 { get; set; }
        public string f生日 { get; set; }
        public string f自我介紹 { get; set; }
        public string f暱稱 { get; set; }
        public string f英文名字 { get; set; }
        public string f性別 { get; set; }
        public string f興趣 { get; set; }
        public string f已占用時間 { get; set; }
        public string f按過讚的文章編號 { get; set; }
    }
}
