//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTravel
    {
        public int f旅遊文章編號 { get; set; }
        public Nullable<int> f團主會員編號 { get; set; }
        public string f文章團主名稱 { get; set; }
        public string f文章發文日期 { get; set; }
        public string f文章活動開始日期 { get; set; }
        public string f文章活動結束日期 { get; set; }
        public string f文章活動招募日期 { get; set; }
        public string f文章標題 { get; set; }
        public string f文章內容 { get; set; }
        public string f文章地區 { get; set; }
        public string f文章預算 { get; set; }
        public string f文章瀏覽次數 { get; set; }
        public string f文章讚數 { get; set; }
        public string f分類 { get; set; }
        public string f標籤 { get; set; }
        public string f文章團圖 { get; set; }
    }
}
