//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTravel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tTravel()
        {
            this.tIdentity = new HashSet<tIdentity>();
        }
    
        public int f旅遊編號 { get; set; }
        public string f旅遊區使用者編號 { get; set; }
        public string f旅遊發文日期 { get; set; }
        public string f旅遊活動開始時間 { get; set; }
        public string f旅遊活動結束時間 { get; set; }
        public string f旅遊招募截止時間 { get; set; }
        public string f旅遊標題 { get; set; }
        public string f旅遊內容 { get; set; }
        public string f旅遊地區 { get; set; }
        public string f旅遊預算 { get; set; }
        public string f旅遊瀏覽次數 { get; set; }
        public string f旅遊讚數 { get; set; }
        public string f旅遊分類 { get; set; }
        public string f旅遊標籤 { get; set; }
        public string f旅遊團圖 { get; set; }
        public string f旅遊按過讚的會員編號 { get; set; }
        public string f旅遊經度 { get; set; }
        public string f旅遊緯度 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tIdentity> tIdentity { get; set; }
    }
}
