//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIIProject_travel
{
    using System;
    using System.Collections.Generic;
    
    public partial class t聯絡我們
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public t聯絡我們()
        {
            this.tIdentity = new HashSet<tIdentity>();
        }
    
        public int f聯絡我們文章編號 { get; set; }
        public string f聯絡我們使用者編號 { get; set; }
        public string f意見內容 { get; set; }
        public string f意見類型 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tIdentity> tIdentity { get; set; }
    }
}
